openapi: 3.0.0
info:
  title: Bedrock Agent to SQS Lambda
  version: 1.0.0
paths:
  /store_conversation_data:
    post:
      summary: Stores conversation data in SQS FIFO queue
      description: Endpoint to store conversation data in an SQS FIFO queue. Invoked by Bedrock agent. Requires user_message, session_id, and timestamp.
      operationId: storeConversationData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_message:
                  type: string
                  description: The user's message.
                conversation_history:
                  type: string
                  description: The full conversation history.
                session_id:
                  type: string
                  description: The unique session ID.
                timestamp:
                  type: string
                  format: date-time
                  description: The timestamp of the message.
              required:
                - user_message
                - session_id
                - timestamp
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message.
                required:
                  - message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating an internal server error.
